In [1]:
import pandas as pd
import numpy as np

# SKLearn ML Models
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

# SKLearn Model Evaluation Functions
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

In [2]:
df = pd.read_csv("Weather_Data.csv")
df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes

In [4]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [5]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

In [7]:
df_sydney_processed.head(10)

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,41,17,20,92,...,False,False,False,False,False,True,False,False,False,False
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,41,9,13,83,...,False,False,False,False,False,False,False,False,False,False
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,41,17,2,88,...,False,False,False,False,False,False,False,False,False,False
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,41,22,20,83,...,False,False,False,False,False,False,False,False,False,False
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,41,11,6,88,...,False,False,False,False,False,False,False,True,False,False
5,2/6/2008,20.2,27.2,1.6,2.6,8.6,41,9,22,69,...,False,False,False,False,False,False,False,False,False,False
6,2/7/2008,18.6,26.3,6.2,5.2,5.2,41,15,15,75,...,False,False,True,False,False,False,False,False,False,False
7,2/8/2008,17.2,22.3,27.6,5.8,2.1,41,7,15,77,...,False,False,False,True,False,False,False,False,False,False
8,2/9/2008,16.4,20.8,12.6,4.8,3.0,41,19,9,92,...,False,False,False,False,False,False,False,True,False,False
9,2/10/2008,14.6,24.2,8.8,4.4,10.1,41,11,20,80,...,False,False,False,False,True,False,False,False,False,False

In [8]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [9]:
df_sydney_processed = df_sydney_processed.astype(float)

In [14]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

features.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,19.5,22.4,15.6,6.2,0.0,41.0,17.0,20.0,92.0,84.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,19.5,25.6,6.0,3.4,2.7,41.0,9.0,13.0,83.0,73.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21.6,24.5,6.6,2.4,0.1,41.0,17.0,2.0,88.0,86.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20.2,22.8,18.8,2.2,0.0,41.0,22.0,20.0,83.0,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19.7,25.7,77.4,4.8,0.0,41.0,11.0,6.0,88.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [25]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, random_state=10, test_size=0.2)

In [31]:
LinearReg = linear_model.LinearRegression()
x = np.asanyarray(features)
y = np.asanyarray(Y)
LinearReg.fit (x, y)

print("Coefficients: ", LinearReg.coef_[:5])
print("Intercept: ", LinearReg.intercept_)

Coefficient:  [-0.02653184  0.00751099  0.00090757  0.00723085 -0.03690619]
Intercept:  -37648656305.60393

In [38]:
predictions = LinearReg.predict(x_test)
LinearRegression_R2=np.mean((predictions - y_test) ** 2)
LinearRegression_MAE= np.mean(np.abs(predictions - y_test))
LinearRegression_MSE=np.square(np.subtract(predictions, y_test)).mean()

Report = {"Metrics":["MAE","MSE","R2"],"Result": 
    [LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2]}

0.11051914047037487

C:\Users\Harsh Jagtap\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

NameError: name 'LinearRegression_MAE' is not defined